// react-todo/src/todo/Todo.jsx
import React from 'react'
import { TodoItem } from "./todo-item/TodoItem";
import { AddTodo } from "./add-todo/AddTodo";

export const Todo = () => {
    const [todos, setTodos] = React.useState([
        {
            id: 1,
            description: 'Сделать презентацию',
            done: false
        },
        {
            id: 2,
            description: 'Сделать лабки',
            done: false
        },
        {
            id: 3,
            description: 'Задизигнить дизайн',
            done: true
        },
        {
            id: 4,
            description: 'Implement drag and drop todo list',
            done: true
        },
        {
            id: 5,
            description: 'Implement todo list',
            done: true
        }
    ])

    const [lastId, setLastId] = React.useState(Math.max(...todos.map(todo => todo.id)))

    const onToggleCheck = todo => {
        const changedTodo = {
            ...todo,
            done: !todo.done
        }

        setTodos(prevTodos => {
            const filteredTodos = prevTodos.filter(t => t.id !== todo.id)
            return [...filteredTodos.filter(t => !t.done), changedTodo, ...filteredTodos.filter(t => t.done)]
        })
    }

    const onToggleRemove = id => {
        setTodos(prevTodos => prevTodos.filter(t => t.id !== id))
    }

    const onToggleAddTodo = description => {
        const newTodo = {
            id: lastId + 1,
            description,
            done: false
        }

        setTodos(prevTodos => [
            newTodo,
            ...prevTodos
        ])
        setLastId(newTodo.id)
    }

    return (
        <div className="todo">
            <div className="todo_header">
                <h4>Список задач</h4>
            </div>

            <AddTodo onToggleAddTodo={onToggleAddTodo}/>

            <div id="todo-list" className="todo_list">
                {todos.map(todo => (
                    <TodoItem
                        key={todo.id}
                        todo={todo}
                        onToggleCheck={onToggleCheck}
                        onToggleRemove={onToggleRemove}
                    />
                ))}
            </div>
        </div>
    )
}

// angular-todo/src/app/todo/todo.component.ts
import { ChangeDetectionStrategy, Component, ElementRef, OnInit, ViewChild } from '@angular/core'
import { Todo } from './todo-item/todo-item.component'
import { animate, query, style, transition, trigger } from '@angular/animations'
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop'

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [
    trigger('todo', [
      transition('* => void', [
        query('.todo_list-item',
          animate(500, style({
            opacity: 0
          }))
        )
      ])
    ])
  ]
})
export class TodoComponent implements OnInit {

  todos: Todo[] = [
    {
      id: 1,
      description: 'Сделать презентацию',
      done: false
    },
    {
      id: 2,
      description: 'Сделать лабки',
      done: false
    },
    {
      id: 3,
      description: 'Задизигнить дизайн',
      done: true
    },
    {
      id: 4,
      description: 'Implement drag and drop todo list',
      done: true
    },
    {
      id: 5,
      description: 'Implement todo list',
      done: true
    }
  ]

  lastId: number

  ngOnInit(): void {
    this.initLastId()
  }

  createNewTask(description: string): void {
    this.todos = [
      {
        id: ++this.lastId,
        description,
        done: false
      },
      ...this.todos
    ]
  }

  onRemove(todo: Todo): void {
    this.todos = this.todos.filter(t => t.id !== todo.id)
  }

  onCheck(todo: Todo): void {
    const changedTodo = {
      id: todo.id,
      description: todo.description,
      done: !todo.done
    }
    const filteredTodos = this.todos.filter(t => t.id !== todo.id)

    this.todos = [...filteredTodos.filter(t => !t.done), changedTodo, ...filteredTodos.filter(t => t.done)]
  }

  drop(event: CdkDragDrop<Todo[]>): void {
    const isSameDoneStatus = this.todos[event.previousIndex].done ?
      this.todos[event.currentIndex].done : !this.todos[event.currentIndex].done

    if (isSameDoneStatus) {
      moveItemInArray(this.todos, event.previousIndex, event.currentIndex)
    }
  }

  private initLastId(): void {
    this.lastId = Math.max(...this.todos.map(todo => todo.id))
  }
}

<div class="todo">
  <div class="todo_header">
    <h4>Список задач</h4>
  </div>

  <app-add-todo (addNew)="createNewTask($event)"></app-add-todo>

  <div cdkDropList class="todo_list" (cdkDropListDropped)="drop($event)">
    <app-todo-item cdkDrag
                   *ngFor="let todo of todos"
                   @todo
                   [todo]="todo"
                   (remove)="onRemove($event)"
                   (check)="onCheck($event)">
    </app-todo-item>
  </div>
</div>
